import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { join } from 'node:path'

import {
  type ChromiumBrowser,
  type SocketOptions,
  getAllNativeMessagingHostsDirs,
  getAllWindowsRegistryKeys,
  getExtensionIds,
  NATIVE_HOST_IDENTIFIER,
  NATIVE_HOST_MANIFEST_NAME,
} from './browser.js'
import { execFileNoThrow, getPlatform, jsonStringify } from './shared.js'
import type { Logger } from './core/types.js'

export type InstallNativeHostOptions = SocketOptions & {
  browsers?: ChromiumBrowser[]
  cliEntryPath: string
  nodeExecutable?: string
  logLevel?: string
  logger?: Logger
  wrapperDirOverride?: string
  manifestDirOverride?: string
  manifestDirsOverride?: Array<{ browser: ChromiumBrowser; path: string }>
  registryKeysOverride?: Array<{ browser: ChromiumBrowser; key: string }>
  registerWindowsKey?: (
    browser: ChromiumBrowser,
    key: string,
    manifestPath: string,
  ) => Promise<boolean>
}

export type InstallNativeHostResult = {
  wrapperPath: string
  manifestPaths: string[]
  registryEntries: string[]
  browsers: ChromiumBrowser[]
}

export function getPackageHomeDir(): string {
  if (process.platform === 'win32') {
    const appData = process.env.APPDATA || join(homedir(), 'AppData', 'Roaming')
    return join(appData, 'claw-in-chrome-mcp')
  }

  return join(homedir(), '.claw-in-chrome-mcp')
}

export function getNativeHostManifestRoot(): string {
  return join(getPackageHomeDir(), 'ChromeNativeHost')
}

export function getDefaultWrapperDir(): string {
  return join(getPackageHomeDir(), 'bin')
}

export function buildNativeHostManifest(wrapperPath: string): string {
  const manifest = {
    name: NATIVE_HOST_IDENTIFIER,
    description: 'Claw in Chrome MCP Native Host',
    path: wrapperPath,
    type: 'stdio',
    allowed_origins: getExtensionIds().map(id => `chrome-extension://${id}/`),
  }

  return jsonStringify(manifest, 2)
}

export async function createWrapperScript(
  cliEntryPath: string,
  options: Pick<InstallNativeHostOptions, 'socketPath' | 'socketDir' | 'logLevel' | 'nodeExecutable' | 'wrapperDirOverride'>,
): Promise<string> {
  const platform = getPlatform()
  const wrapperDir = options.wrapperDirOverride ?? getDefaultWrapperDir()
  const wrapperPath =
    platform === 'windows'
      ? join(wrapperDir, 'chrome-native-host.bat')
      : join(wrapperDir, 'chrome-native-host')

  const nodeExecutable = options.nodeExecutable ?? process.execPath
  const cliArgs = ['chrome-native-host']
  if (options.logLevel) {
    cliArgs.push('--log-level', options.logLevel)
  }
  if (options.socketPath) {
    cliArgs.push('--socket-path', options.socketPath)
  }
  if (options.socketDir) {
    cliArgs.push('--socket-dir', options.socketDir)
  }

  const command =
    platform === 'windows'
      ? buildWindowsCommand(nodeExecutable, cliEntryPath, cliArgs)
      : buildPosixCommand(nodeExecutable, cliEntryPath, cliArgs)

  const scriptContent =
    platform === 'windows'
      ? `@echo off\r\nREM Generated by claw-in-chrome-mcp\r\n${command}\r\n`
      : `#!/bin/sh\n# Generated by claw-in-chrome-mcp\nexec ${command}\n`

  const existing = await readFile(wrapperPath, 'utf8').catch(() => null)
  if (existing !== scriptContent) {
    await mkdir(wrapperDir, { recursive: true })
    await writeFile(wrapperPath, scriptContent, 'utf8')
    if (platform !== 'windows') {
      await chmod(wrapperPath, 0o755)
    }
  }

  return wrapperPath
}

export async function installNativeHost(
  options: InstallNativeHostOptions,
): Promise<InstallNativeHostResult> {
  const platform = getPlatform()
  const wrapperPath = await createWrapperScript(options.cliEntryPath, options)
  const manifestContent = buildNativeHostManifest(wrapperPath)
  const selectedBrowsers = options.browsers ?? []
  const browsers = selectedBrowsers.length > 0 ? selectedBrowsers : Object.keys(getDefaultBrowserMap()) as ChromiumBrowser[]
  const manifestPaths: string[] = []
  const registryEntries: string[] = []

  if (platform === 'windows') {
    const manifestDir = options.manifestDirOverride ?? getNativeHostManifestRoot()
    const manifestPath = join(manifestDir, NATIVE_HOST_MANIFEST_NAME)
    await mkdir(manifestDir, { recursive: true })
    await writeFileIfChanged(manifestPath, manifestContent)
    manifestPaths.push(manifestPath)

    const registryKeys = options.registryKeysOverride ?? getAllWindowsRegistryKeys(selectedBrowsers.length > 0 ? selectedBrowsers : undefined)
    for (const { browser, key } of registryKeys) {
      const fullKey = `${key}\\${NATIVE_HOST_IDENTIFIER}`
      const ok = options.registerWindowsKey
        ? await options.registerWindowsKey(browser, fullKey, manifestPath)
        : await registerWindowsNativeHost(fullKey, manifestPath)
      if (ok) {
        registryEntries.push(fullKey)
      }
    }
  } else {
    const manifestDirs = options.manifestDirsOverride ?? getAllNativeMessagingHostsDirs(selectedBrowsers.length > 0 ? selectedBrowsers : undefined)
    for (const { path } of manifestDirs) {
      const manifestPath = join(path, NATIVE_HOST_MANIFEST_NAME)
      await mkdir(path, { recursive: true })
      await writeFileIfChanged(manifestPath, manifestContent)
      manifestPaths.push(manifestPath)
    }
  }

  options.logger?.info('[install-native-host] Wrapper: %s', wrapperPath)
  for (const manifestPath of manifestPaths) {
    options.logger?.info('[install-native-host] Manifest: %s', manifestPath)
  }

  return {
    wrapperPath,
    manifestPaths,
    registryEntries,
    browsers,
  }
}

async function registerWindowsNativeHost(fullKey: string, manifestPath: string): Promise<boolean> {
  const result = await execFileNoThrow('reg', [
    'add',
    fullKey,
    '/ve',
    '/t',
    'REG_SZ',
    '/d',
    manifestPath,
    '/f',
  ])
  return result.code === 0
}

async function writeFileIfChanged(path: string, content: string): Promise<void> {
  const existing = await readFile(path, 'utf8').catch(() => null)
  if (existing === content) {
    return
  }
  await writeFile(path, content, 'utf8')
}

function buildWindowsCommand(nodeExecutable: string, cliEntryPath: string, args: string[]): string {
  const quoted = [nodeExecutable, cliEntryPath, ...args].map(quoteWindowsArg).join(' ')
  return quoted
}

function buildPosixCommand(nodeExecutable: string, cliEntryPath: string, args: string[]): string {
  const quoted = [nodeExecutable, cliEntryPath, ...args].map(quotePosixArg).join(' ')
  return quoted
}

function quoteWindowsArg(value: string): string {
  const escaped = value.replace(/"/g, '""')
  return `"${escaped}"`
}

function quotePosixArg(value: string): string {
  return `'${value.replace(/'/g, `'"'"'`)}'`
}

function getDefaultBrowserMap(): Record<ChromiumBrowser, true> {
  return {
    chrome: true,
    brave: true,
    arc: true,
    chromium: true,
    edge: true,
    vivaldi: true,
    opera: true,
  }
}
